language: php

# optionally set up exclusions and allowed failures in the matrix
matrix:
  include:
  - php: 7.0
    dist: xenial
    env:
      - DB=pgsql
    sudo: required
    services:
      - postgresql
      
# extensiones
before_install:

addons:
    apt:
        packages:
        - php7.0-xml
        - php7.0-mbstring
        - php7.0-mcrypt
        - php7.0-gd
        - php7.0-zip
        - php7.0-pgsql
install:
  - wget https://github.com/isurgob/isurgob/archive/master.zip
  - unzip master.zip
  
# execute any number of scripts before the test run, custom env's are available as variables
before_script:
  - cd db
  - psql -h localhost -U postgres -f "a-pgbackup_sam_logico-2019-05.sql";
  - psql -h localhost -U postgres -f "b-pgbackup_sam_dataaux-2019-05.sql";

# notifications
notifications:
  email: "sandracmart@gmail.com"